name: Build, test and push container
on:
  push:
    tags:
      - '*'

jobs:
  build-test-push:
    uses: QCDIS/KMS-generic/.github/workflows/build-test-push.yml@main
    with:
      docker_folder: KMS-generic
      tag: kms-generic
      push: true
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
