name: Build and test container
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 5 * *'

jobs:
  build-test-push:
    uses: QCDIS/KMS-generic/.github/workflows/build-test-push.yml@main
    with:
      docker_folder: KMS-generic
      tag: kms-generic
      push: false
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
