name: Build and test container
on:
  release:
    types: [published]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 0 5 * *'

jobs:
  build-test-push:
    uses: ./.github/workflows/build-test-push.yml
    with:
      docker_folder: .
      tag: kms-generic
      push: ${{ github.event_name == 'release' }}
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
